apiVersion: v1
kind: Service
metadata:
  name: {{ include "geocontrib.fullname" . }}-frontend-svc
  labels:
    {{- include "geocontrib.labels" . | nindent 4 }}-frontend-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "geocontrib.selectorLabels" . | nindent 4 }}-frontend-depl
