apiVersion: v1
kind: Service
metadata:
  name: {{ include "geocontrib.fullname" . }}-geocontrib-svc
  labels:
    {{- include "geocontrib.labels" . | nindent 4 }}-geocontrib-svc
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "geocontrib.selectorLabels" . | nindent 4 }}-geocontrib-depl
